import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { options, authUrl } from "../config";
import { Header } from "../components/header/header";
import { cookies } from "next/headers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

  fetch(authUrl, options)
    .then(res => res.json())
    .catch(err => console.error(err));
  
  const cookieStore = await cookies();
  const sessionId = cookieStore.get('tmdb_session')?.value;
    
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <Header sessionId={sessionId}/>
        <div className="main-wrapper">{children}</div>
        
      </body>
    </html>
  );
}
